# Generated by Django 4.2.2 on 2023-08-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_alter_episode_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(null=True, upload_to="courses"),
        ),
    ]
